# Generated by Django 5.2.4 on 2025-10-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='background_color',
            field=models.CharField(default='#0f719b', help_text='Color de fondo para imágenes verticales (formato hexadecimal, ej: #0f719b)', max_length=7),
        ),
    ]
